package br.ufrn.dimap.middleware.remotting.interfaces;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;

/**
 * Represents a Marshaller, which is used for
 * generating (marshalling) and interpreting (unmarshalling)
 * byte stream representations of objects to be transmitted
 * over the network, optionally converting them to a structured
 * marshalling format beforehand (e.g. XML, CDR, etc).
 * 
 * @author carlosemv
 */
public interface MarshallerI {
	/**
	 * Generates byte stream that represents object.
	 * 
	 * @param object 	the object to be marshalled
	 * @return 	byte stream representation of object
	 */
	public ByteArrayOutputStream marshal(Object object) throws IOException;
	
	/**
	 * Interprets byte stream generated by an instance
	 * of the same Marshaller implementation into its
	 * corresponding object.
	 * 
	 * @param inputStream	marshalled object as byte stream
	 * @return 	object represented by inputStream
	 */
	public Object unmarshal(ByteArrayInputStream byteStream) throws IOException, ClassNotFoundException ;
}
